version: "3"
services:
  app:
    build: .
    restart: always
    depends_on: 
      - mongoDbLive
    volumes: 
      - .:/usr/src/app
    ports:
      - "4000:4000"
    links:
      - mongoDbLive
  mongoDbLive:
    image: mongo
    restart: always
    ports:
      - "27017:27017"